### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by GLShary** [lcdm-uiuc/PyIF#1]
Hello,
Sorry to bother you. I tried to run your program, but the transfer entropy turned out to be negative. According to the definition of transfer entropy, it is mutual information and should be a positive number. Can you explain it for me? Thank you and it will be really nice of you!

**Comment by mlhossen** [comment]
Hi @Shania6201, Were you able to calculate the transfer entropy with this PyIF?

**Comment by nicrie** [comment]
I can confirm, I also get negative TE in some cases.

**Comment by fishbacp** [comment]
Same here.

**Comment by ikegwukc** [comment]
Hello sorry for the delay in response. 

For the example in the README the Transfer Entropy estimate will be 0 or negative since there's no information transfer between X and Y.  There are both random noise.

In theory, Transfer Entropy (TE ) should be greater than 0, however, in the code, we implement the Kraskov estimator which is skewed downward. So if you end up with a TE estimate that is negative it is likely that there's no information transfer between the two processes. 

For a link to understand the estimator we implement, see this paper: https://arxiv.org/abs/cond-mat/0305641 

Currently, this code is not being actively maintained or monitored. There may be plans in the near future to work on this.
